### ISSUE TITLE
Component not found

### ISSUE THREAD

**Issue by JNussenzveig** [vtex-apps/product-summary-context#6]
When trying to add `vtex.product-summary-context` to my `manifest.json` dependencies, the following error is returned:

```
{
  "message": "Component not found: vtex.product-summary-context@0.3.0/useProductSummary",
  "path": [
    "pageBlocks"
  ],
  "extensions": {
    "message": "Component not found: vtex.product-summary-context@0.3.0/useProductSummary",
    "available": [
      "ProductSummaryContext"
    ],
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
      "message": "Component not found: vtex.product-summary-context@0.3.0/useProductSummary",
      "name": "Error",
      "stack": "Error: Component not found: vtex.product-summary-context@0.3.0/useProductSummary\n    at AppsConfigsSource.resolveComponentEntry (/usr/src/node/v2/configurators/appsConfigsSource/appsConfigsSource.ts:440:13)\n    at /usr/src/node/v2/configurators/appsConfigsSource/appsConfigsSource.ts:449:30\n    at Array.reduce (<anonymous>)\n    at AppsConfigsSource.resolveComponentEntry (/usr/src/node/v2/configurators/appsConfigsSource/appsConfigsSource.ts:446:37)\n    at XWrap.f (/usr/src/node/v2/configurators/appsConfigsSource/appsConfigsSource.ts:385:35)\n    at XWrap.@@transducer/step (/usr/local/data/service/node_modules/ramda/src/internal/_xwrap.js:12:17)\n    at _arrayReduce (/usr/local/data/service/node_modules/ramda/src/internal/_reduce.js:11:34)\n    at _reduce (/usr/local/data/service/node_modules/ramda/src/internal/_reduce.js:45:12)\n    at Object.f3 [as reduce] (/usr/local/data/service/node_modules/ramda/src/internal/_curry3.js:47:14)\n    at AppsConfigsSource.getComponents (/usr/src/node/v2/configurators/appsConfigsSource/appsConfigsSource.ts:374:12)\n    at exports.pageBlocks (/usr/src/node/v2/resolvers/pageBlocks.ts:180:46)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at /usr/src/node/v2/index.ts:38:20\n    at async Promise.all (index 0)\n    at runHttpQuery (/usr/local/app/node_modules/@vtex/api/lib/service/worker/runtime/graphql/middlewares/run.js:7:22)\n    at /usr/local/app/node_modules/@vtex/api/lib/utils/time.js:73:13",
      "extensions": {
        "message": "Component not found: vtex.product-summary-context@0.3.0/useProductSummary",
        "available": [
          "ProductSummaryContext"
        ]
      }
    }
  },
  "name": "GraphQLError",
  "forwardedHost": "dev--miriadeit.myvtex.com",
  "operationId": "f7dcbc41-e730-4ea0-9240-21f7475b9a90",
  "query": {
    "query": "query pageBlocks($input: PageBlocksInput) {\n  pageBlocks(input: $input) {\n    appsEtag\n    appsSettingsJSON\n    blocksJSON\n    blocksTreeJSON\n    componentsJSON\n    contentMapJSON\n    extensionsJSON\n    appsMessages {\n      key\n      message {\n        from\n        context\n        content\n      }\n    }\n    userMessages {\n      key\n      message {\n        from\n        context\n        content\n      }\n    }\n    page {\n      blockId\n      canonical\n      canonicalPath\n      disableExternals\n      domain\n      metaTags {\n        description\n        keywords\n      }\n      routeContextLocator\n      routeId\n      routePath\n      paramsMapJSON\n      paramsJSON\n      pageContext {\n        id\n        type\n      }\n      title\n      varyContentById\n    }\n    pagesJSON\n    cacheHintsJSON\n    runtimeJSON\n  }\n}",
    "variables": "{\"input\":{\"contentType\":\"department\",\"depTree\":\"[{\\\"id\\\":\\\"vtex.transform-render-sms@0.1.7\\\",\\\"location\\\":\\\"/miriadeit/dev/apps/vtex.transform-render-sms@0.1.7\\\",\\\"registry\\\":\\\"vtex\\\",\\\"vendor\\\":\\\"vtex\\\",\\\"name\\\":\\\"transform-render-sms\\\",\\\"version\\\":\\\"0.1.7\\\",\\\"settingsSchema\\\":{},\\\"credentialType\\\":\\\"absolute\\\",\\\"_buildFeatures\\\":null,\\\"_activationDate\\\":\\\"Thu May  2 13:52:42 UTC 2019\\\",\\\"_resolvedDependencies\\\":{\\\"infra:service-dotnet\\\":\\\"0.7.1\\\",\\\"vtex.messages-templates\\\":\\\"0.10.1\\\",\\\"vtex.messenger-core\\\":\\\"0.1.9\\\",\\\"vtex.render-server\\\":\\\"8.114.0\\\"},\\\"_isRoot\\\":true},{\\\"id\\\":\\\"vtex.render-runtime@8.99.0\\\",\\\"location\\\":\\\"/miriadeit/dev/apps/vtex.render-runtime@8.99.0\\\",\\\"registry\\\":\\\"vtex\\\",\\\"vendor\\\":\\\"vtex\\\",\\\"name\\\":\\\"render-runtime\\\",\\\"version\\\":\\\"8.99.0\\\",\\\"settingsSchema\\\":{},\\\"credentialType\\\":\\\"absolute\\\",\\\"_buildFeatures\\\":{\\\"vtex.docs-graphql\\\":[\\\"build.json\\\",\\\"build.json\\\"],\\\"vtex.render-server\\\":[\\\"build.json\\\"]},\\\"_activationDate\\\":\\\"Mon Jan  1 00:00:00 UTC 0 [Truncated: variables too long]"
  },
  "requestId": "6e16da4707df4cb5aa7fcf9a08f767ee",
  "pathName": "pageBlocks"
}
```
<img width="1680" alt="Screen Shot 2020-04-15 at 11 03 44" src="https://user-images.githubusercontent.com/7662734/79346470-cd5b4c80-7f08-11ea-9071-a2f0b435390f.png">

Relevant code:

```
import React from 'react'
import { useProductSummary } from 'vtex.product-summary-context'
import { Spinner } from 'vtex.styleguide'
import { ExtensionPoint } from 'vtex.render-runtime'

const ProductSummaryWishlist = () => {

  const { product, isLoading } = useProductSummary()

  if (isLoading) return <Spinner />

  console.log("product", product);

  return (
    <div>
      <ExtensionPoint id="addButton" skuId={product.id} />
    </div>
  );
}

export default ProductSummaryWishlist
```

Our client needs this ASAP, can someone help me?

**Comment by klzns** [comment]
You should import it like this:

```jsx
import { useProductSummary } from 'vtex.product-summary-context/ProductSummaryContext'
```

**Comment by klzns** [comment]
Example: 
https://github.com/vtex-apps/product-summary/blob/master/react/components/ProductSummaryBrand/ProductSummaryBrand.js#L5
